### ISSUE TITLE
Add Windows Launch On Install Example

### ISSUE THREAD

**Issue by wiverson** [wiverson/maven-jpackage-template#12]
Integrate the Windows installer enhancement to add launch on completion.

https://gist.github.com/wiverson/45bbd58d928b4735ad141163579c4201

**Comment by wiverson** [comment]
Done.

**Comment by HydrolienF** [comment]
Hey I would like to do the same thing on my Java app.
Don't you fined any easieset way than using this js script to do that ?

**Comment by HydrolienF** [comment]
At least the .js working for me to 😃
