### ISSUE TITLE
Debugging a failing startup app / including FXML files

### ISSUE THREAD

**Issue by antmordel** [wiverson/maven-jpackage-template#16]
First, thanks a lot for this repo. It's very useful.

I have this template with Spring Boot included. When I generate the installer, it's not starting (and it doesn't produce any error). Once we have the `jlink-ed` runtime image, is there any way we can run our jar on this image to see what outputs produce?

On another note, I have the views in FMXL, and they are in `src/main/resources/views`. Do you have any experience bundling these views within the resulting artefacts?

Thanks a lot.

**Comment by wiverson** [comment]
Glad you like it! :)

I’m away from my computer this week, so just off the cuff from my phone:

- check the main method of BaseApplication to see how to route output to a temp file to debug via logging as a fallback.
- I think you have to add the resource directory back into the pom under the resources section to pick up the FXML. This is technically a bug as I override the resources config in the pom to process build info.
- I’m sure there is a way to run (eg via the JavaFX plugin) on a built jlink vm but I’d have to dig into it next week. In practice when doing dev I usually just use the JavaFX plugin run most of the time, and then just do sanity checks to make sure it runs on the jlink JVM.  Other plugins such as surefire and exec I believe let you specify a target vm.

**Comment by antmordel** [comment]
Thanks a lot, @wiverson. This enormously unblock my work.

I was going in circles doing:
- using _Spring Maven Plugin_, thus getting a non-canonical JAR and having troubles but having the Resources
- Adding the resources manually in the pom, but still not getting the inside the `jar` under `./target/dependency`

I don't want to disturb your time away of the laptop!

Many thanks.

**Comment by wiverson** [comment]
I just committed a tweak to the template that adds the default Maven resources directory back in, so I'm going to close this issue. LMK if you have any other Qs!

**Comment by antmordel** [comment]
Many thanks @wiverson !!
