### ISSUE TITLE
[bug] when launching app on Windows app is launch in background

### ISSUE THREAD

**Issue by HydrolienF** [wiverson/maven-jpackage-template#17]
That's not a big issue but you can probably fix it easily.
If app is launch by the .msi installer it is launch under the explorer. (I don't see the window the 1st time I try the app because my explorer was in full screen).

A fix in Java Swing will be to add 
```java
super.setAlwaysOnTop(true);
super.toFront();
super.requestFocus();
super.setAlwaysOnTop(false);
```
at the end of the window constructor.

![Capture d’écran (1258)](https://user-images.githubusercontent.com/71718798/121325803-358d9e80-c912-11eb-88af-e897317c1bbb.png)

**Comment by wiverson** [comment]
Very cool workaround. I've seen it happen sometimes on Windows, but not all the time. Windows focus can be kind of strange.

Feel free to send a PR and/or I'll do eventually.

**Comment by HydrolienF** [comment]
It work for me now
