### ISSUE TITLE
MAVEN_OPTS="--add-modules jdk.incubator.jpackage" not working on windows

### ISSUE THREAD

**Issue by oforshaddy** [wiverson/maven-jpackage-template#2]
adding *MAVEN_OPTS="--add-modules jdk.incubator.jpackage"*  to env on windows does not yield appropriate results when mvn --version is ran.  this is what it produces as output on windows: 

***Unrecognized option: --add-modules jdk.incubator.jpackage*
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.**

How can this be solved ?

**Comment by wiverson** [comment]
What is the output of running java --version at the command line?

**Comment by wiverson** [comment]
Was able to repro. Don't put the --add-modules jdk.incubator.jpackage inside of quotes in the Windows env variable pane.
<img width="437" alt="mvn opts for windows" src="https://user-images.githubusercontent.com/873850/105227433-28fcdb00-5b16-11eb-9686-2e8972140150.png">

**Comment by wiverson** [comment]
Let me know if this works. If not, feel free to reopen.

**Comment by oforshaddy** [comment]
Thanks.
This works
