### ISSUE TITLE
Spaces in project path cause jpackage to fail to run

### ISSUE THREAD

**Issue by kodingcrypto** [wiverson/maven-jpackage-template#21]
![image](https://user-images.githubusercontent.com/55035861/126289840-c4d54521-1c6f-4265-b973-322692a92e11.png)
[myLog.txt](https://github.com/wiverson/maven-jpackage-template/files/6846757/myLog.txt)

I need help.
This is my log when creating windows installer.
Thank you.

**Comment by wiverson** [comment]
Looks like it's complaining about the space in your path - specifically the JavaFX JDK16 portion of the path.

Try renaming the folder to remove the space. Alternatively, you could try adding quote marks inside the win-jpackage.txt around the command, but removing the space is probably easier/faster.

Generally speaking I would strongly suggest avoiding spaces in any development related path as a matter of habit. This kind of dumb thing is common, especially when dealing with scripts that invoke native tooling. This is technically probably a bug in the template, but you'll run into this stuff all the time.

**Comment by kodingcrypto** [comment]
Thank you very much

The solution works

**Comment by wiverson** [comment]
I'm going to leave this open as a bug for now - perhaps someone will want to take a stab at adding the proper escaping to the windows packaging file and/or will run into a similar issue. :)

**Comment by wiverson** [comment]
Added quote marks protection to macOS and Windows builds, so I'm going to go ahead and close this for now.
