### ISSUE TITLE
Building for both Mac Intel & M1 using Github Actions

### ISSUE THREAD

**Issue by Luthien-in-edhil** [wiverson/maven-jpackage-template#24]
Hello again!

Just a question this time*: I picked up the dictionary app again after that ordeal of getting it to build on Windows & Mac last spring and because one of the people who want to test it has a new Mac M1. The Intel build fails to run on his machine, as expected.

Do you think that if could work to build both a M1- and an Intel-compatible Mac OS version of the app (next to the Windows- and Linux builds) using the Github Actions, by duplicating the Mac branch and using the M1 native JDK / JFX libraries in that new branch?

Thanks in advance! 
I see there have been some changes to the template since I last built it, so I'll first try things out in the existing configuration.

_(*) famous last words ... 😨_

**Comment by wiverson** [comment]
Hey! Hope you are well!

I just added some notes to the README for the project on M1 Mac stuff. AFAIK there are no M1 GitHub Action runners, and I don't think you can have an Intel version of the JDK assemble an M1 version via jlink.

The Intel version of the app *should* run via Rosetta. Might want to grab logs and see what's up with that.

I'm going to click the fancy button to convert this to a discussion. :)
