### ISSUE TITLE
Maven variable typo

### ISSUE THREAD

**Issue by AIGLEZMA** [wiverson/maven-jpackage-template#34]
When opening the Start Menu the folder (of the app vendor) is ${vendor} instead of what you entered in ${windows.vendor}, i'm not sure if the developer forgot this or not

https://github.com/wiverson/maven-jpackage-template/blob/3e0b28e7f4854fdc295b62e24e7dbe00081a5c40/src/packaging/win-jpackage.txt#L4

**Comment by wiverson** [comment]
Yup, basically just a typo. Feel free to submit a PR or I'll get around to it at some point.
