### ISSUE TITLE
Odd Installer Behaviour

### ISSUE THREAD

**Issue by hrzafer** [wiverson/maven-jpackage-template#40]
I have two projects with this template. When I run the installer created with one, it removes the installation files of the other during install.

run ProjectA.msi -> see that it is installed under C:\Program Files\ProjectA
run ProjectB.msi -> see that it is installed under C:\Program Files\ProjectB also see that files under `C:\Program Files\ProjectA` are gone.

And this is both ways. ProjectA installer uninstalls ProjectB and vice versa.

**Comment by hrzafer** [comment]
Figured out that I had forgotten to change the Windows UUID. Close this issue. Thanks.

**Comment by wiverson** [comment]
ha, beat me too it. Glad you figured it out. Going to convert this to discussion so it'll be a bit easier for folks to find.
