### ISSUE TITLE
Fix for finding file identifier in add-launch-to-msi.js

### ISSUE THREAD

**Issue by mcantrell** [wiverson/maven-jpackage-template#46]
jpackage created an MSI with a LongFileName|ShortFileName format which caused the lookup to fail. I ended up using the FindFileIdentifier function in this post to resolve the identifier:

https://stackoverflow.com/a/1681410

You may want to consider enhancing your script to account for these differences if you stumble upon the same issue.

**Comment by wiverson** [comment]
This is great, probably explains an error someone else ran into. I'll merge it in after the holidays, or if you want to send in a PR that would be great.

**Comment by hrzafer** [comment]
Replacing this part:

```
sql = "SELECT File from File where FileName='${app.name}.exe'";
view = database.OpenView(sql);
view.Execute();
var file = view.Fetch().StringData(1)
WScript.StdErr.WriteLine(file);
view.Close();

```

with

```
var file = FindFileIdentifier(database, "${app.name}.exe");
```

worked.

Thanks.

**Comment by hrzafer** [comment]
BTW what is the command line equivalent of the goal in the `exec-maven-plugin` for this? It must be something like:

```
cd target
cscript packaging/add-launch-to-msi.js [SOME OPTIONS  HERE]
```

I don't want to run `mvn:install` for every try.

**Comment by wiverson** [comment]
Updated template to use @hrzafer fix.
