### ISSUE TITLE
Adding external addtional resource files

### ISSUE THREAD

**Issue by oforshaddy** [wiverson/maven-jpackage-template#5]
There are no parameters adding additional resource files _**(outside the src folder)**_ different from the resources in the resource directory. I want add some configuration files which are located outside the src folder to be included in the native bundle. Is there a way I can add the path for those files, so that when installed they are installed together with the app on the install path ?

**Comment by wiverson** [comment]
That's outside the scope of this template, more of a general Maven usage question.

From what you are describing, you probably want to use the standard maven-resources-plugin, as described here:

https://www.baeldung.com/maven-resources-plugin

You can attach the execution to a reasonable lifecycle spot that makes sense for your build.
